CREATE TABLE "main"."member" (
  "id"         INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  "name"       TEXT NOT NULL UNIQUE
);

--

CREATE TABLE "main"."key" (
  "id"         INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  "uuid"       TEXT NOT NULL UNIQUE,
  "member_id"  INTEGER REFERENCES "member"(id) ON DELETE SET NULL
);