name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Vet
        run: go vet -v ./...

      - name: install tools
        working-directory: $(GOPATH)
        run: |
          go install -u golang.org/x/lint/golint
          go install -u github.com/kisielk/errcheck
          go install honnef.co/go/tools/cmd/staticcheck

      - name: Rurest
        run: |
          golint $(go list ./... )
          staticcheck ./...
          out=$$(gofmt -s -l -d -e $(gofile) | tee /dev/stderr);
          if [ -n "$$out" ];
            then exit 1;
          fi;
          errcheck -verbose ./...

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...
